title = "Hoot Works"
baseURL = "https://hoot.works/"
languageCode = "en-gb"
enableRobotsTXT = true
theme = "hootworks"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]

  name = "Hoot Works Limited"
  description = ""
