title = "Hoot Works"
baseURL = "https://hoot.works/"
languageCode = "en-gb"
enableRobotsTXT = true
theme = "hootworks"
disableKinds = ["taxonomy", "taxonomyTerm"]
contentDir = "content"

[params]
  name = "Hoot Works Limited"
  email = "info@hoot.works"
  description = "Media Technology Consultancy & Software Development"
